### ISSUE TITLE
Transforms is not valid in femto bolt.

### ISSUE THREAD

**Issue by Tacha-S** [orbbec/OrbbecSDK_ROS1#16]
If it were similar to Azure Kinect, `camera_link` and `color_frame` should be parallel, with `depth_frame` slightly pitched downward relative to `camera_link`. However, when starting FEMTO BOLT, the TF results in `camera_link` and `depth_frame` being parallel, with `color_frame` slightly pitched downward relative to `camera_link`.

**Comment by Tacha-S** [comment]
Could you share CAD or URDF of femto bolt?

**Comment by bmegli** [comment]
@Tacha-S, what I see in current master (54ca6bcb54ccc731879d4ea155dd9836de8c62f6) looks reasonable 

![image](https://github.com/orbbec/OrbbecSDK_ROS1/assets/9095769/4a3aae3e-e0d7-44f8-89b3-fa62fba1c6e0)

Adding `camera_link`
- parallel to RGB
- seems to share origin with `camera_depth_frame`
- `camera_depth_frame` is tilted down as in Kinect4A

![image](https://github.com/orbbec/OrbbecSDK_ROS1/assets/9095769/5fe96b06-5b34-4084-b36d-ec9c3c2494ac)

**Comment by bmegli** [comment]
This seems to be the relevant commit:
- https://github.com/orbbec/OrbbecSDK_ROS1/commit/95a2ce690408d08cd530b13045cd71570762ee41

Looks a bit overly optimistic
- assuming zero rotation for color
- assuming zero translation for depth

But maybe this is assumption in factory calibration

**Comment by bmegli** [comment]
## Depth

```bash
rosrun tf tf_echo camera_link camera_depth_frame
At time 1705344616.484
- Translation: [0.000, 0.000, 0.000]
- Rotation: in Quaternion [-0.004, 0.053, -0.001, 0.999]
            in RPY (radian) [-0.009, 0.107, -0.003]
            in RPY (degree) [-0.514, 6.105, -0.176]
```

## Color

```bash
rosrun tf tf_echo camera_link camera_color_frame
At time 1705344666.276
- Translation: [-0.006, -0.032, -0.001]
- Rotation: in Quaternion [0.000, 0.000, 0.000, 1.000]
            in RPY (radian) [0.000, -0.000, 0.000]
            in RPY (degree) [0.000, -0.000, 0.000]
```

**Comment by Tacha-S** [comment]
Thank you for the information. It has been corrected, so I will close this.
