### ISSUE TITLE
/home/alex/work/Camera/orbbercamer/devel/lib/orbbec_camera/orbbec_camera_node: symbol lookup error: /home/alex/work/Camera/orbbercamer/devel/lib/liborbbec_camera.so: undefined symbol: _ZN6google10LogMessage6streamEv

### ISSUE THREAD

**Issue by Alexjiand** [orbbec/OrbbecSDK_ROS1#34]
when I run roslaunch orbbec_camera astra.launch, this error occured. Anyone know why this happened?

**Comment by jian-dong** [comment]
Could you please let me know which version of Ubuntu you are using, and whether you have installed Google Glog? The error message you provided indicates a symbol lookup error related to Google Glog in your Orbbec camera node

**Comment by jian-dong** [comment]
glog deps is removed
