### ISSUE TITLE
Femto Mega I support

### ISSUE THREAD

**Issue by bmegli** [orbbec/OrbbecSDK_ROS1#46]
Is Femto Mega I supported by this driver?

As I understand Femto Mega I only supports ethernet interface.

-----------------------------------------------------------------------------------

This issue:
- https://github.com/orbbec/OrbbecSDK_ROS1/issues/6
- suggests that it should be supported

Readme supported hardware:
- https://github.com/orbbec/OrbbecSDK_ROS1?tab=readme-ov-file#supported-hardware-products
  - guides to OrbbecSDK support
    - https://github.com/orbbec/OrbbecSDK?tab=readme-ov-file#product-support
    - which mentions Femto Mega
      - but doesn't mention Femto Mega I

------------------------------------------------------------------------------------------

Could you clarify support for Femto Mega I?

**Comment by zhonghong322** [comment]
What are the firmware version and SDK version of your Mega I device?

**Comment by bmegli** [comment]
Hi @zhonghong322,

This is theoretical question. 

Other Femto variants are listed as supported in docs:
- https://github.com/orbbec/OrbbecSDK?tab=readme-ov-file#product-support

Is Femto Mega I not supported or just not listed?

**Comment by bmegli** [comment]
Clarified in 295d8ea593728a70388a9d557868c25054aeb107
