### ISSUE TITLE
Access Femto Mega through ethernet interface

### ISSUE THREAD

**Issue by akashjinandra** [orbbec/OrbbecSDK_ROS1#6]
I have a femto mega that's running on a x86 based PC running Ubuntu 20 and ROS noetic.

 I haven't been able to find any documentation on how to access or talk to the Femto Mega through the ethernet interface, Is there a default IP or settings to change in the ROS driver?

**Comment by jian-dong** [comment]
@akashjinandra Current, I did not add ethernet access for ROS; I think the next release will be added. cc @zhonghong322

**Comment by akashjinandra** [comment]
Is there any more effort on this? We would like to switch from the USB interface.

**Comment by chengshans** [comment]
I encountered the same problem when using the Femto Mega I camera, is there any countermeasure now? Thanks.

**Comment by akashjinandra** [comment]
Yes this is fully working in the latest release
